name:                DinnersShoppingList
version:             0.1.0.0
github:              "grudus/DinnersShoppingList"
license:             MIT
author:              "grudus"
maintainer:          "dupa@dupa.com"
copyright:           "2019 grudus"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/grudus/DinnersShoppingList#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - bytestring

executables:
  DinnersShoppingList-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - DinnersShoppingList

tests:
  DinnersShoppingList-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - DinnersShoppingList
    - hspec
